#!/usr/bin/env bash
# Regenerates assets.h from resources/loader-assets/'s background PNGs: decodes
# each to raw RGBA8888 pixels (ImageMagick) and embeds them as plain C byte
# arrays (xxd -i). The point of this being pre-decoded rather than embedding
# the PNG files themselves: the running program never parses/decodes
# anything at startup -- no libpng, no image-decoding step at all between
# opening the X display and blitting pixels, which is the whole reason this
# project exists (see main.c's own top comment).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

SRC_DIR="../resources/loader-assets"
OUT="assets.h"

WIDTH="$(identify -format '%w' "$SRC_DIR/background_light.png")"
HEIGHT="$(identify -format '%h' "$SRC_DIR/background_light.png")"

{
    echo "// Generated by generate_assets.sh from $SRC_DIR -- do not hand-edit."
    echo "#pragma once"
    echo
    echo "#define IMG_WIDTH ${WIDTH}"
    echo "#define IMG_HEIGHT ${HEIGHT}"
    echo
} > "$OUT"

for name in light dark; do
    convert "$SRC_DIR/background_${name}.png" -depth 8 RGBA:- | xxd -i -n "${name}_rgba" >> "$OUT"
    echo >> "$OUT"
done

echo "wrote $OUT ($(wc -c < "$OUT") bytes source)"
